"""sinking funds: funds table, transaction fund_id, scenario fund adjustments

Revision ID: 1d0caa0187df
Revises: 31dd6252df2f
Create Date: 2026-08-28 13:14:26.493802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0caa0187df'
down_revision: Union[str, Sequence[str], None] = '31dd6252df2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('annual_amount_cents', sa.Integer(), nullable=False),
    sa.Column('entry_amount_cents', sa.Integer(), nullable=True),
    sa.Column('entry_unit', sa.String(), nullable=True),
    sa.Column('entry_period_n', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('start_month', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # Explicit FK names: SQLite batch mode rebuilds the table and needs a
    # name to reference (see fastapi-sqlite-scaffold design notes).
    with op.batch_alter_table('scenario_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_kind', sa.String(), server_default='recurring', nullable=False))
        batch_op.add_column(sa.Column('target_fund_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_scenario_adjustments_target_fund_id', 'funds',
            ['target_fund_id'], ['id'], ondelete='CASCADE',
        )

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transactions_fund_id', 'funds', ['fund_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_fund_id', type_='foreignkey')
        batch_op.drop_column('fund_id')

    with op.batch_alter_table('scenario_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scenario_adjustments_target_fund_id', type_='foreignkey')
        batch_op.drop_column('target_fund_id')
        batch_op.drop_column('add_kind')

    op.drop_table('funds')
    # ### end Alembic commands ###
