"""daily spread and daily spend

Revision ID: 426c93f63d8a
Revises: 5eac41ea42d9
Create Date: 2026-10-04 10:06:08.329068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426c93f63d8a'
down_revision: Union[str, Sequence[str], None] = '5eac41ea42d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_item_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recurring_item_id'], ['recurring_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_spend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_spend_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_spend_recurring_item_id'), ['recurring_item_id'], unique=False)

    with op.batch_alter_table('recurring_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spread_daily', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_items', schema=None) as batch_op:
        batch_op.drop_column('spread_daily')

    with op.batch_alter_table('daily_spend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_spend_recurring_item_id'))
        batch_op.drop_index(batch_op.f('ix_daily_spend_date'))

    op.drop_table('daily_spend')
    # ### end Alembic commands ###
