"""recurring day_of_week + week_anchor

Revision ID: be94e37f6c91
Revises: da823197cc8d
Create Date: 2026-08-29 20:33:13.398531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be94e37f6c91'
down_revision: Union[str, Sequence[str], None] = 'da823197cc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week_anchor', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_items', schema=None) as batch_op:
        batch_op.drop_column('week_anchor')
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
