"""trip settlements

Revision ID: d17f8183844f
Revises: 1d0caa0187df
Create Date: 2026-08-28 14:56:23.803769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17f8183844f'
down_revision: Union[str, Sequence[str], None] = '1d0caa0187df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('override_amount_cents', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('settled_transaction_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['settled_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_settlements')
    # ### end Alembic commands ###
