"""month opening balances and app settings

Revision ID: d560d63cde14
Revises: 426c93f63d8a
Create Date: 2026-10-05 08:39:22.589120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd560d63cde14'
down_revision: Union[str, Sequence[str], None] = '426c93f63d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('month_opening_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    # ### end Alembic commands ###

    # The balance rollover chain starts the month this is deployed: earlier
    # months weren't tracked as a balance, so they open at $0 and don't roll.
    op.execute(
        "INSERT INTO app_settings (key, value) "
        "VALUES ('rollover_start_month', strftime('%Y-%m', 'now'))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('month_opening_balances')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
