"""payment deferrals

Revision ID: e19cbb24387b
Revises: be94e37f6c91
Create Date: 2026-10-02 10:59:42.398100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19cbb24387b'
down_revision: Union[str, Sequence[str], None] = 'be94e37f6c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_deferrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_item_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('original_month', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['origin_id'], ['payment_deferrals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurring_item_id'], ['recurring_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_id', name='uq_payment_deferrals_origin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_deferrals')
    # ### end Alembic commands ###
